### ISSUE TITLE
1. Discuss your initial thoughts in details on how you will design this application?

### ISSUE THREAD

**Issue by JoshEddie** [tdtrevathan/group12#1]

**Comment by stillOscar** [comment]
**Answer:** Given that we need to design an application that will need to store client information, including a client’s location, purchase history, gallons request, company profit margin, username, password, and other profile information, we understand that we will need some form of database management software to store and manipulate this information. To construct this aspect of our program, we are considering using mySQL since it is a standard tool for the task and there is strong familiarity with the software within our group. We will also require frontend technologies to implement the user interface through which a client will register, log in, and manage his/her profile and are considering HTML, CSS, and JavaScript (React.js) for this implementation, largely due to the strong affinity members of our group have for this suite of software. For the corresponding backend implementation needed to handle things like server-side logic, user authentication, profile management, and fuel quote calculations, we are considering software like Node.js with Express or Python with Django since these technologies are sufficient for this task and provide an opportunity for learning for some members (Node.js) or are understood well by team members (Python). To limit the effects of potential mistakes and accommodate the learning process of team members, we will implement version control using Git so that our team will be able to effectively collaborate on this project while also tracking changes to our source code. Moreover, we will delegate tasks using the issues assignment feature on GitHub, allowing us to allocate tasks equally in a documented way.

**Comment by stillOscar** [comment]
**Updated Answer:** Given that we need to design an application that will need to store client information, including a client’s location, purchase history, gallons request, company profit margin, username, password, and other profile information, we understand that we will need some form of database management software to store and manipulate this information. To construct this aspect of our program, we are considering using mySQL since it is a standard tool for the task and there is strong familiarity with the software within our group. We will also require frontend technologies to implement the user interface through which a client will register, log in, and manage his/her profile and are considering HTML, CSS, and JavaScript (React.js) for this implementation, largely due to the strong affinity members of our group have for this suite of software. For the corresponding backend implementation needed to handle things like server-side logic, user authentication, profile management, and fuel quote calculations, we are considering Java since the language can host various libraries like Spring Boot and Quarkus that offer features to handle these processes, and, given the languages’ relative similarity to C++, would be relatively straightforward for team members who are not yet familiar to learn. To limit the effects of potential mistakes and accommodate the learning process of team members, we will implement version control using Git so that our team will be able to effectively collaborate on this project while also tracking changes to our source code. Moreover, we will delegate tasks using the issues assignment feature on GitHub, allowing us to allocate tasks equally in a documented way.
