### ISSUE TITLE
2. Discuss what development methodology you will use and why?

### ISSUE THREAD

**Issue by JoshEddie** [tdtrevathan/group12#2]

**Comment by kaylagoldsmith** [comment]
**Answer:** For our project, we decided to go with the Waterfall Methodology. In short, this method is a straightforward project management system that progresses linearly. Meaning the only way we could continue through the project utilizing this method is by completing the phases one by one. This is the main reason as to why we choose to use the Waterfall Method, because everything that we needed to know and understand about this project was given to us at the beginning. This signifies that the requirements for our project are fixed and consistent, which allows us to progress through the project linearly step by step.
