### ISSUE TITLE
2. Discuss if your design and development methodology has changed since assignment 1 and why? (1 point)

### ISSUE THREAD

**Issue by JoshEddie** [tdtrevathan/group12#21]
2. Discuss if your design and development methodology has changed since assignment 1 and why? (1 point)

**Comment by stillOscar** [comment]
**Answer:** From Assignment 1, the design of our application and our development methodology has not changed. Our technology choices remain the same with MySQL being used for database management, HTML, CSS, and JavaScript (React.js) constituting our front end technologies, and Java being used to handle backend development. We have chosen to carry on with these tools since they are technologies our team members have experience using or could benefit from learning and because they are standard systems for application construction that allow us to satisfy the complex requirements of our project. The quick implementation of key front end features further proved to us that we had chosen adequate pieces of software to make strong headway on our project. In terms of project management methodology, the Waterfall method remains our strategy of choice since it coincides well with the iterative development process the class’s assignments set out for us, whereby we will have to complete a modular piece of our application before working on the next piece. This method remains in favor since it offers us clarity in terms of project progression and requirements by delineating a clear plan of action through various well-defined phases of development. Moreover, our system architecture remains consistent with our initial plan, whereby we segment our application into distinct layers and modules that handle distinct operations and data. This approach allows us to better understand the complexity of our application by defining and categorizing each constituent part of our project. This approach also lends itself well to collaboration since there are distinct blocks of tasks that can be assigned to team members. Overall, our design and development methodologies have persisted from the previous assignment due to their suitability and the absence of compelling reasons to deviate from them. We further believe that consistency will be a critical component for the successful execution of our project.
